CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE user_role AS ENUM ('client','admin');
CREATE TYPE project_status AS ENUM ('discovery','design','development','testing','client_review','final_delivery','completed');
CREATE TYPE invoice_status AS ENUM ('draft','sent','paid','overdue','void');
CREATE TYPE payment_method AS ENUM ('bank_transfer','card','cash','other');

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), auth0_sub text UNIQUE NOT NULL, email text UNIQUE NOT NULL, name text NOT NULL, role user_role NOT NULL DEFAULT 'client', avatar_url text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE clients (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, company_name text NOT NULL, phone text, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE, name text NOT NULL, slug text NOT NULL, summary text, status project_status NOT NULL DEFAULT 'discovery', progress integer NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100), total_price numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_price >= 0), monthly_minimum numeric(12,2) NOT NULL DEFAULT 0 CHECK (monthly_minimum >= 0), currency char(3) NOT NULL DEFAULT 'TRY', start_date date, due_date date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(client_id, slug));
CREATE TABLE project_members (project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'client', PRIMARY KEY(project_id,user_id));
CREATE TABLE milestones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, title text NOT NULL, description text, due_date date, completed_at timestamptz, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, amount numeric(12,2) NOT NULL CHECK (amount > 0), currency char(3) NOT NULL DEFAULT 'TRY', paid_at date NOT NULL DEFAULT CURRENT_DATE, method payment_method NOT NULL DEFAULT 'bank_transfer', reference text, note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, number text UNIQUE NOT NULL, amount numeric(12,2) NOT NULL CHECK (amount >= 0), status invoice_status NOT NULL DEFAULT 'draft', due_date date, issued_at date, paid_at date, payment_id uuid REFERENCES payments(id) ON DELETE SET NULL, storage_key text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE files (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, uploaded_by uuid NOT NULL REFERENCES users(id), name text NOT NULL, storage_key text UNIQUE NOT NULL, mime_type text NOT NULL, size_bytes bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id) ON DELETE CASCADE, actor_id uuid NOT NULL REFERENCES users(id), kind text NOT NULL, title text NOT NULL, body text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, author_id uuid NOT NULL REFERENCES users(id), body text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX projects_client_idx ON projects(client_id); CREATE INDEX payments_project_idx ON payments(project_id); CREATE INDEX files_project_idx ON files(project_id); CREATE INDEX activities_project_idx ON activities(project_id); CREATE INDEX messages_project_idx ON messages(project_id);
CREATE OR REPLACE VIEW project_financials AS SELECT p.id AS project_id, p.total_price, p.monthly_minimum, COALESCE(SUM(pay.amount),0)::numeric(12,2) AS amount_paid, GREATEST(p.total_price-COALESCE(SUM(pay.amount),0),0)::numeric(12,2) AS remaining_balance FROM projects p LEFT JOIN payments pay ON pay.project_id=p.id GROUP BY p.id;
