import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Bell, ChevronDown, CircleDollarSign, ClipboardList, CreditCard, FileText, FolderOpen, LayoutDashboard, LogOut, Menu, MessageSquare, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Users, X } from "lucide-react";
import { getNeonToken, neonClient, neonConfigured } from "./lib/neon";
import "./App.css";

type ProjectStatus = "discovery" | "design" | "development" | "testing" | "client_review" | "final_delivery" | "completed";
const statusOrder: ProjectStatus[] = ["discovery", "design", "development", "testing", "client_review", "final_delivery", "completed"];
const statusLabel: Record<ProjectStatus, string> = { discovery: "Discovery", design: "Design", development: "Development", testing: "Testing", client_review: "Client Review", final_delivery: "Final Delivery", completed: "Completed" };
type Project = { id: string; name: string; status: ProjectStatus; progress: number; total_price: number | string; currency: string; company_name?: string; amount_paid?: number | string; remaining_balance?: number | string; due_date?: string | null };
type Client = { id: string; company_name: string; phone?: string; notes?: string; user_id?: string; email: string; name: string; project_count?: number };

async function apiFetch(path: string, init: RequestInit = {}) { const token = await getNeonToken(); return fetch(path, { ...init, headers: { ...(init.headers || {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); }

function DemoLogin() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [signUp, setSignUp] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!neonClient) return; setLoading(true); setError(""); const result = signUp ? await neonClient.auth.signUp.email({ name: email.split("@")[0] || "Client", email, password }) : await neonClient.auth.signIn.email({ email, password }); setLoading(false); if (result.error) setError(result.error.message || "Authentication failed"); else window.location.reload(); }
  return <div className="login-shell"><form className="login-card" onSubmit={submit}><div className="brand-mark">H</div><p className="eyebrow">HERMES SOFTWARE / CLIENT PORTAL</p><h1>Good work<br /><span>ships together.</span></h1><p className="muted">A private workspace for project progress, files, invoices and the next move.</p><label className="login-label">EMAIL<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="you@company.com" /></label><label className="login-label">PASSWORD<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={8} placeholder="••••••••" /></label>{error && <p className="login-error">{error}</p>}<button className="button button-green wide" disabled={loading}>{loading ? "CONNECTING…" : signUp ? "CREATE ACCOUNT" : "ENTER PORTAL"} <ChevronDown size={16} /></button><button type="button" className="text-button login-toggle" onClick={() => setSignUp(!signUp)}>{signUp ? "Already have an account? Sign in" : "Need an account? Sign up"}</button><small>Protected by Neon Managed Auth · Better Auth</small></form></div>;
}

function App() { if (!neonConfigured) return <PortalApp />; return <NeonAuthApp />; }
function NeonAuthApp() { const [user, setUser] = useState<{ name?: string; email?: string } | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { neonClient?.auth.getSession().then((result) => { setUser(result.data?.user || null); setLoading(false); }); }, []); if (loading) return <div className="loading">LOADING HERMES PORTAL<span>_</span></div>; if (!user) return <DemoLogin />; return <PortalApp userName={user.name || user.email || "Client"} onLogout={async () => { await neonClient?.auth.signOut(); setUser(null); }} />; }

function PortalApp({ userName = "Client", onLogout }: { userName?: string; onLogout?: () => void }) {
  const initialSection = window.location.pathname === "/admin" ? "Overview" : "Dashboard";
  const [section, setSection] = useState(initialSection); const [mobileNav, setMobileNav] = useState(false); const [toast, setToast] = useState(""); const [admin, setAdmin] = useState(false); const [role, setRole] = useState("client"); const [projects, setProjects] = useState<Project[]>([]); const [clients, setClients] = useState<Client[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const clientNav = [["Dashboard", LayoutDashboard], ["Projects", ClipboardList], ["Payments", CreditCard], ["Files", FolderOpen], ["Messages", MessageSquare]] as const; const adminNav = [["Overview", LayoutDashboard], ["Clients", Users], ["Projects", ClipboardList], ["Payments", CircleDollarSign], ["Invoices", FileText], ["Files", FolderOpen], ["Activity", ShieldCheck], ["Settings", Settings]] as const;
  useEffect(() => { let active = true; (async () => { try { const me = await apiFetch("/api/me"); if (!me.ok) throw new Error(`Profile API failed (${me.status})`); const meData = await me.json(); const projectsResponse = await apiFetch("/api/projects"); if (!projectsResponse.ok) throw new Error(`Projects API failed (${projectsResponse.status})`); const projectData = await projectsResponse.json(); const isAdmin = meData.user?.role === "admin"; let clientData: Client[] = []; if (isAdmin) { const clientsResponse = await apiFetch("/api/clients"); if (clientsResponse.ok) clientData = (await clientsResponse.json()).clients || []; } if (active) { setRole(meData.user?.role || "client"); setProjects(projectData.projects || []); setClients(clientData); setAdmin(isAdmin); } } catch (error) { if (active) setLoadError(error instanceof Error ? error.message : "Portal data failed to load"); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, []);
  const nav = admin ? adminNav : clientNav; const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); }; const refresh = async () => { const response = await apiFetch("/api/projects"); if (response.ok) setProjects((await response.json()).projects || []); }; const refreshClients = async () => { const response = await apiFetch("/api/clients"); if (response.ok) setClients((await response.json()).clients || []); };
  return <div className="portal"><aside className={`sidebar ${mobileNav ? "open" : ""}`}><div className="side-brand"><div className="brand-mark small">H</div><span>HERMES<br /><b>PORTAL</b></span><button className="mobile-close" onClick={() => setMobileNav(false)}><X size={18} /></button></div><div className="side-label">WORKSPACE</div><nav>{nav.map(([label, Icon]) => <button key={label} className={section === label ? "active" : ""} onClick={() => { setSection(label); setMobileNav(false); }}><Icon size={17} />{label}</button>)}</nav><div className="sidebar-bottom">{role === "admin" && <button onClick={() => setAdmin(!admin)}><ShieldCheck size={17} />{admin ? "Client view" : "Admin view"}</button>}<button onClick={onLogout || (() => notify("Sign out is available after authentication."))}><LogOut size={17} />Sign out</button></div></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(true)}><Menu size={20} /></button><div><p className="eyebrow">{admin ? "ADMIN / HERMES SOFTWARE" : `HELLO, ${userName.toUpperCase()}`}</p><h2>{section}</h2></div><div className="top-actions"><button className="icon-button" onClick={() => notify("You’re all caught up.")}><Bell size={18} /></button><div className="user-chip"><span className="avatar">{userName.slice(0, 1).toUpperCase()}</span><span>{userName}</span><ChevronDown size={14} /></div></div></header><div className="content">{loadError && <div className="notice error"><b>{loadError}</b><br /><small>Auth session token could not reach the server. Refresh after signing in again.</small></div>}{loading ? <div className="loading inline">LOADING DATA<span>_</span></div> : admin ? <AdminView section={section} projects={projects} clients={clients} notify={notify} onRefresh={refresh} onRefreshClients={refreshClients} /> : <ClientView projects={projects} notify={notify} />}</div></main>{toast && <div className="toast">{toast}</div>}</div>;
}

function ClientView({ projects, notify }: { projects: Project[]; notify: (message: string) => void }) { const item = projects[0]; if (!item) return <div className="empty-state"><p className="eyebrow">NO ACTIVE PROJECTS</p><h1>Your workspace is ready.</h1><p className="muted">Hermes will add your first project here when the engagement starts.</p></div>; const total = Number(item.total_price || 0); const paid = Number(item.amount_paid || 0); const remaining = Number(item.remaining_balance ?? total - paid); return <><section className="hero-row"><div><p className="eyebrow">ACTIVE PROJECT / {item.company_name || "HERMES CLIENT"}</p><h1>{item.name}</h1><p className="muted">{statusLabel[item.status]} · live from your Hermes workspace.</p></div><button className="button button-dark" onClick={() => notify("Message composer ready.")}><MessageSquare size={16} /> MESSAGE HERMES</button></section><section className="grid-12"><div className="panel progress-panel span-8"><div className="panel-top"><div><p className="eyebrow">CURRENT STATUS</p><h3>{statusLabel[item.status]}</h3></div><span className="status-pill green">LIVE</span></div><div className="progress-number">{item.progress}<small>%</small></div><div className="progress-track"><span style={{ width: `${item.progress}%` }} /></div><div className="status-rail">{statusOrder.map((status) => <div key={status} className={statusOrder.indexOf(status) <= statusOrder.indexOf(item.status) ? "done" : ""}><i />{statusLabel[status]}</div>)}</div></div><div className="panel span-4 price-panel"><p className="eyebrow">PROJECT VALUE</p><div className="price">₺{total.toLocaleString("tr-TR")}</div><div className="money-line"><span>Paid</span><b>₺{paid.toLocaleString("tr-TR")}</b></div><div className="money-line"><span>Remaining</span><b className="green-text">₺{remaining.toLocaleString("tr-TR")}</b></div><div className="due-date">Financial totals calculated server-side</div></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">PROJECTS</p><h3>Your active work</h3></div><button className="text-button" onClick={() => notify(`${projects.length} project${projects.length === 1 ? "" : "s"} loaded.`)}>REFRESHED FROM NEON →</button></div><div className="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Progress</th><th>Balance</th></tr></thead><tbody>{projects.map((project) => <tr key={project.id}><td><b>{project.name}</b><small>{project.company_name || "Hermes client"}</small></td><td><span className="status-pill green">{statusLabel[project.status]}</span></td><td>{project.progress}%</td><td>₺{Number(project.remaining_balance || 0).toLocaleString("tr-TR")}</td></tr>)}</tbody></table></div></section></>; }

function AdminView({ section, projects, clients, notify, onRefresh, onRefreshClients }: { section: string; projects: Project[]; clients: Client[]; notify: (message: string) => void; onRefresh: () => Promise<void>; onRefreshClients: () => Promise<void> }) {
  const [editing, setEditing] = useState<Project | null>(null); const [editingClient, setEditingClient] = useState<Client | null>(null); const [showClientForm, setShowClientForm] = useState(false); const [showProjectForm, setShowProjectForm] = useState(false); const [saving, setSaving] = useState(false);
  const [projectDraft, setProjectDraft] = useState({ clientId: clients[0]?.id || "", name: "", summary: "", totalPrice: "", currency: "TRY" });
  const cards = [{ label: "Active projects", value: String(projects.length), delta: "Live from Neon", icon: ClipboardList }, { label: "Outstanding", value: `₺${projects.reduce((sum, p) => sum + Number(p.remaining_balance || 0), 0).toLocaleString("tr-TR")}`, delta: "Calculated server-side", icon: CircleDollarSign }, { label: "Clients", value: String(clients.length), delta: "Manage accounts", icon: Users }, { label: "Files", value: "Optional", delta: "R2 not required", icon: FolderOpen }];
  async function saveProject(event: FormEvent) { event.preventDefault(); if (!editing) return; setSaving(true); const response = await apiFetch("/api/projects", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: editing.id, name: editing.name, status: editing.status, progress: editing.progress, totalPrice: editing.total_price, dueDate: editing.due_date }) }); setSaving(false); if (!response.ok) notify(`Project update failed (${response.status}).`); else { setEditing(null); await onRefresh(); notify("Project updated in Neon."); } }
  async function createProject(event: FormEvent) { event.preventDefault(); setSaving(true); const response = await apiFetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ clientId: projectDraft.clientId, name: projectDraft.name, summary: projectDraft.summary, totalPrice: Number(projectDraft.totalPrice || 0), currency: projectDraft.currency }) }); setSaving(false); if (!response.ok) notify(`Project create failed (${response.status}).`); else { setShowProjectForm(false); await onRefresh(); notify("Project created in Neon."); } }
  async function saveClient(event: FormEvent) { event.preventDefault(); if (!editingClient) return; setSaving(true); const response = await apiFetch("/api/clients", { method: editingClient.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: editingClient.id, email: editingClient.email, name: editingClient.name, companyName: editingClient.company_name, phone: editingClient.phone, notes: editingClient.notes }) }); setSaving(false); if (!response.ok) notify(`Client save failed (${response.status}).`); else { setShowClientForm(false); setEditingClient(null); await onRefreshClients(); notify("Client saved in Neon."); } }
  if (section === "Clients") return <><section className="hero-row"><div><p className="eyebrow">CRM / CLIENT ACCOUNTS</p><h1>People you ship with.</h1><p className="muted">Create a customer record first. When they sign up with the same email, the account is linked automatically.</p></div><button className="button button-green" onClick={() => { setEditingClient({ id: "", company_name: "", email: "", name: "" }); setShowClientForm(true); }}><Plus size={16} /> NEW CLIENT</button></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">CLIENTS / {clients.length}</p><h3>Customer accounts</h3></div><div className="search-box"><Search size={15} /><input placeholder="Search clients" /></div></div><div className="table-wrap"><table><thead><tr><th>Contact</th><th>Company</th><th>Projects</th><th>Phone</th><th /></tr></thead><tbody>{clients.map((client) => <tr key={client.id}><td><b>{client.name}</b><small>{client.email}</small></td><td>{client.company_name}</td><td>{client.project_count || 0}</td><td>{client.phone || "—"}</td><td><button className="icon-button" onClick={() => { setEditingClient(client); setShowClientForm(true); }}><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div></section>{showClientForm && editingClient && <ClientModal value={editingClient} setValue={setEditingClient} saving={saving} onClose={() => setShowClientForm(false)} onSubmit={saveClient} />}</>;
  return <><section className="hero-row"><div><p className="eyebrow">OPERATIONS / LIVE DATA</p><h1>Keep shipping.</h1><p className="muted">The studio, one clean view. Every number comes from Neon.</p></div><button className="button button-green" onClick={() => { if (!clients.length) { notify("Create a client first."); return; } setProjectDraft({ clientId: clients[0].id, name: "", summary: "", totalPrice: "", currency: "TRY" }); setShowProjectForm(true); }}><Plus size={16} /> NEW PROJECT</button></section><div className="stats-grid">{cards.map(({ label, value, delta, icon: Icon }) => <div className="stat-card" key={label}><Icon size={19} /><p className="eyebrow">{label}</p><strong>{value}</strong><span>{delta}</span></div>)}</div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">PROJECTS / ALL CLIENTS</p><h3>Active work</h3></div><div className="search-box"><Search size={15} /><input placeholder="Search projects" /></div></div><div className="table-wrap"><table><thead><tr><th>Project</th><th>Client</th><th>Status</th><th>Progress</th><th>Balance</th><th /></tr></thead><tbody>{projects.map((item) => <tr key={item.id}><td><b>{item.name}</b><small>{statusLabel[item.status]}</small></td><td>{item.company_name || "—"}</td><td><span className="status-pill green">{statusLabel[item.status]}</span></td><td><div className="mini-progress"><span style={{ width: `${item.progress}%` }} /></div>{item.progress}%</td><td>₺{Number(item.remaining_balance || 0).toLocaleString("tr-TR")}</td><td><button className="icon-button" onClick={() => setEditing(item)}><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div></section>{editing && <ProjectEditModal value={editing} setValue={setEditing} saving={saving} onClose={() => setEditing(null)} onSubmit={saveProject} />}{showProjectForm && <ProjectModal value={projectDraft} clients={clients} setValue={setProjectDraft} saving={saving} onClose={() => setShowProjectForm(false)} onSubmit={createProject} />}</>;
}

function ProjectEditModal({ value, setValue, saving, onClose, onSubmit }: { value: Project; setValue: (value: Project) => void; saving: boolean; onClose: () => void; onSubmit: (event: FormEvent) => void }) { return <div className="modal-backdrop"><form className="modal-card" onSubmit={onSubmit}><div className="panel-heading"><div><p className="eyebrow">EDIT PROJECT</p><h3>{value.name}</h3></div><button type="button" className="icon-button" onClick={onClose}><X size={17} /></button></div><label className="login-label">NAME<input value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label><label className="login-label">STATUS<select value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value as ProjectStatus })}>{statusOrder.map((status) => <option key={status} value={status}>{statusLabel[status]}</option>)}</select></label><label className="login-label">PROGRESS<input type="number" min="0" max="100" value={value.progress} onChange={(event) => setValue({ ...value, progress: Number(event.target.value) })} /></label><button className="button button-green wide" disabled={saving}>{saving ? "SAVING…" : "SAVE TO NEON"}</button></form></div>; }

function ProjectModal({ value, clients, setValue, saving, onClose, onSubmit }: { value: { clientId: string; name: string; summary: string; totalPrice: string; currency: string }; clients: Client[]; setValue: (value: { clientId: string; name: string; summary: string; totalPrice: string; currency: string }) => void; saving: boolean; onClose: () => void; onSubmit: (event: FormEvent) => void }) { return <div className="modal-backdrop"><form className="modal-card" onSubmit={onSubmit}><div className="panel-heading"><div><p className="eyebrow">NEW PROJECT</p><h3>Start a project</h3></div><button type="button" className="icon-button" onClick={onClose}><X size={17} /></button></div><label className="login-label">CLIENT<select required value={value.clientId} onChange={(event) => setValue({ ...value, clientId: event.target.value })}>{clients.map((client) => <option key={client.id} value={client.id}>{client.company_name} · {client.name}</option>)}</select></label><label className="login-label">PROJECT NAME<input required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} placeholder="Website redesign" /></label><label className="login-label">SUMMARY<textarea value={value.summary} onChange={(event) => setValue({ ...value, summary: event.target.value })} placeholder="What are we shipping?" /></label><label className="login-label">TOTAL PRICE<input type="number" min="0" value={value.totalPrice} onChange={(event) => setValue({ ...value, totalPrice: event.target.value })} placeholder="45000" /></label><button className="button button-green wide" disabled={saving}>{saving ? "CREATING…" : "CREATE PROJECT"}</button></form></div>; }

function ClientModal({ value, setValue, saving, onClose, onSubmit }: { value: Client; setValue: (value: Client) => void; saving: boolean; onClose: () => void; onSubmit: (event: FormEvent) => void }) { return <div className="modal-backdrop"><form className="modal-card" onSubmit={onSubmit}><div className="panel-heading"><div><p className="eyebrow">{value.id ? "EDIT CLIENT" : "NEW CLIENT"}</p><h3>Client account</h3></div><button type="button" className="icon-button" onClick={onClose}><X size={17} /></button></div><label className="login-label">FULL NAME<input required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label><label className="login-label">EMAIL<input required type="email" value={value.email} onChange={(event) => setValue({ ...value, email: event.target.value })} /></label><label className="login-label">COMPANY<input required value={value.company_name} onChange={(event) => setValue({ ...value, company_name: event.target.value })} /></label><label className="login-label">PHONE<input value={value.phone || ""} onChange={(event) => setValue({ ...value, phone: event.target.value })} /></label><label className="login-label">NOTES<textarea value={value.notes || ""} onChange={(event) => setValue({ ...value, notes: event.target.value })} /></label><button className="button button-green wide" disabled={saving}>{saving ? "SAVING…" : "SAVE CLIENT"}</button></form></div>; }

export default App;
