import { createHash } from "node:crypto";
import { requireActor, json, isAdmin } from "./_lib/auth.js";
import { requireDb } from "./_lib/db.js";
import { projectClientUserId, sendPushToAdmins, sendPushToUserIds } from "./_lib/push.js";

const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const requestMeta = (request: Request) => {
  const candidate = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || request.headers.get("x-real-ip")?.trim() || null;
  const ip = candidate && /^[0-9a-fA-F:.]+$/.test(candidate) && candidate.length <= 45 ? candidate : null;
  return { ip, userAgent: request.headers.get("user-agent") || null };
};
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[character] || character));
function renderMarkdown(markdown: string) {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n"); let html = ""; let inList = false;
  const inline = (value: string) => escapeHtml(value).replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>").replace(/__([^_]+)__/g, "<strong>$1</strong>").replace(/\*([^*]+)\*/g, "<em>$1</em>");
  for (const line of lines) { const trimmed = line.trim(); if (!trimmed) { if (inList) { html += "</ul>"; inList = false; } continue; } const heading = trimmed.match(/^(#{1,3})\s+(.+)$/); const bullet = trimmed.match(/^[-*]\s+(.+)$/); if (heading) { if (inList) { html += "</ul>"; inList = false; } html += `<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`; } else if (bullet) { if (!inList) { html += "<ul>"; inList = true; } html += `<li>${inline(bullet[1])}</li>`; } else { if (inList) { html += "</ul>"; inList = false; } html += `<p>${inline(trimmed)}</p>`; } } if (inList) html += "</ul>"; return html;
}
const fields = "a.id,a.project_id,a.title,a.document_type,a.content,a.content_hash,a.terms_version,a.legal_notice,a.status,a.requested_at,a.read_confirmed_at,a.approved_at,a.approved_by_name,a.approved_by_email,a.approval_hash,p.name AS project_name,c.company_name";
const present = (row: any): any => ({ ...row, content_html: renderMarkdown(String(row.content || "")) });

export const GET = async (request: Request) => {
  try { const actor = await requireActor(request); const db = requireDb(); const rows = isAdmin(actor)
    ? await db`SELECT a.id,a.project_id,a.title,a.document_type,a.content,a.content_hash,a.terms_version,a.legal_notice,a.status,a.requested_at,a.read_confirmed_at,a.approved_at,a.approved_by_name,a.approved_by_email,a.approval_hash,false AS legal_acknowledged,false AS identity_declared,p.name AS project_name,c.company_name FROM digital_approvals a JOIN projects p ON p.id=a.project_id JOIN clients c ON c.id=p.client_id ORDER BY a.created_at DESC LIMIT 200`
    : await db`SELECT a.id,a.project_id,a.title,a.document_type,a.content_hash,a.terms_version,a.legal_notice,a.status,a.requested_at,a.read_confirmed_at,a.approved_at,a.approved_by_name,a.approved_by_email,a.approval_hash,EXISTS (SELECT 1 FROM approval_events e WHERE e.approval_id=a.id AND e.actor_id=u.id AND e.event_type='legal_acknowledged') AS legal_acknowledged,EXISTS (SELECT 1 FROM approval_events e WHERE e.approval_id=a.id AND e.actor_id=u.id AND e.event_type='identity_declared') AS identity_declared,p.name AS project_name,c.company_name,a.content FROM digital_approvals a JOIN projects p ON p.id=a.project_id JOIN clients c ON c.id=p.client_id JOIN users u ON u.id=c.user_id WHERE u.auth0_sub=${actor.sub} ORDER BY a.created_at DESC LIMIT 100`;
    return json({ approvals: rows.map(present).map((row) => { if (!isAdmin(actor)) { const { content: _raw, ...clientRow } = row; return clientRow; } return row; }) });
  } catch (error) { if (error instanceof Response) return error; console.error(error); return json({ error: "Approvals could not be loaded" }, { status: 500 }); }
};

export const POST = async (request: Request) => {
  try { const actor = await requireActor(request); if (!isAdmin(actor)) return json({ error: "Forbidden" }, { status: 403 }); const body = await request.json(); if (!body.projectId || !body.title || !body.content) return json({ error: "projectId, title and content are required" }, { status: 400 }); const db = requireDb(); const project = await db`SELECT id FROM projects WHERE id=${body.projectId} LIMIT 1`; if (!project.length) return json({ error: "Project not found" }, { status: 404 }); const content = String(body.content).trim(); const contentHash = hash(content); const rows = await db`INSERT INTO digital_approvals (project_id,title,document_type,content,content_hash) VALUES (${body.projectId},${String(body.title).trim()},${body.documentType || "project_approval"},${content},${contentHash}) RETURNING id,project_id,title,document_type,content,content_hash,terms_version,legal_notice,status,requested_at,read_confirmed_at,approved_at`; const actorRows = await db`SELECT id FROM users WHERE auth0_sub=${actor.sub} LIMIT 1`; if (actorRows.length) await db`INSERT INTO approval_events (approval_id,actor_id,event_type,metadata) VALUES (${rows[0].id},${actorRows[0].id},'created',${JSON.stringify({ contentHash, termsVersion: rows[0].terms_version })}::jsonb)`; const clientUserId = await projectClientUserId(body.projectId); if (clientUserId) await sendPushToUserIds([clientUserId], { title: "Approval requested", body: `${String(body.title).trim()} is ready for your review.`, url: "/" }).catch((error) => console.error("push approval notification failed", error)); return json({ approval: { ...rows[0], content_html: renderMarkdown(content) } }, { status: 201 }); }
  catch (error) { if (error instanceof Response) return error; console.error(error); return json({ error: "Approval could not be created" }, { status: 500 }); }
};

export const PATCH = async (request: Request) => {
  try { const actor = await requireActor(request); if (isAdmin(actor)) return json({ error: "Only the client can complete this document" }, { status: 403 }); const body = await request.json(); if (!body.id) return json({ error: "id is required" }, { status: 400 }); const db = requireDb(); const found = await db`SELECT a.id,a.project_id,a.title,a.content_hash,a.terms_version,a.read_confirmed_at,u.id AS user_id,u.name,u.email FROM digital_approvals a JOIN projects p ON p.id=a.project_id JOIN clients c ON c.id=p.client_id JOIN users u ON u.id=c.user_id WHERE a.id=${body.id} AND u.auth0_sub=${actor.sub} AND a.status='pending' LIMIT 1`; if (!found.length) return json({ error: "Approval not found or not available" }, { status: 404 }); const meta = requestMeta(request);
    if (body.action === "read") { if (body.readConfirmed !== true) return json({ error: "You must confirm that you read the complete document" }, { status: 400 }); const rows = await db`UPDATE digital_approvals SET read_confirmed_at=COALESCE(read_confirmed_at,now()),read_by=${found[0].user_id},read_ip_address=${meta.ip},read_user_agent=${meta.userAgent} WHERE id=${found[0].id} AND status='pending' RETURNING id,read_confirmed_at`; if (!rows.length) return json({ error: "Approval is no longer pending" }, { status: 409 }); await db`INSERT INTO approval_events (approval_id,actor_id,event_type,ip_address,user_agent,metadata) VALUES (${found[0].id},${found[0].user_id},'read_confirmed',${meta.ip},${meta.userAgent},${JSON.stringify({ contentHash: found[0].content_hash, termsVersion: found[0].terms_version })}::jsonb)`; return json({ approval: rows[0] }); }
    if (!found[0].read_confirmed_at) return json({ error: "Document must be read and confirmed before approval" }, { status: 400 });
    if (body.action === "legal_ack") { if (body.legalAccepted !== true) return json({ error: "Legal acknowledgement is required" }, { status: 400 }); await db`INSERT INTO approval_events (approval_id,actor_id,event_type,ip_address,user_agent,metadata) VALUES (${found[0].id},${found[0].user_id},'legal_acknowledged',${meta.ip},${meta.userAgent},${JSON.stringify({ contentHash: found[0].content_hash, termsVersion: found[0].terms_version, legalAccepted: true })}::jsonb)`; return json({ ok: true, stage: "legal_acknowledged" }); }
    if (body.action === "identity_confirm") { if (body.identityConfirmed !== true || !String(body.signatureName || "").trim()) return json({ error: "Identity declaration and typed legal name are required" }, { status: 400 }); await db`INSERT INTO approval_events (approval_id,actor_id,event_type,ip_address,user_agent,metadata) VALUES (${found[0].id},${found[0].user_id},'identity_declared',${meta.ip},${meta.userAgent},${JSON.stringify({ contentHash: found[0].content_hash, typedName: String(body.signatureName).trim() })}::jsonb)`; return json({ ok: true, stage: "identity_declared" }); }
    if (body.action !== "approve" || body.confirmed !== true || body.legalAccepted !== true || body.identityConfirmed !== true || !String(body.signatureName || "").trim()) return json({ error: "Complete all three approval stages before final approval" }, { status: 400 });
    const stages = await db`SELECT event_type FROM approval_events WHERE approval_id=${found[0].id} AND actor_id=${found[0].user_id} AND event_type IN ('legal_acknowledged','identity_declared') GROUP BY event_type`;
    if (!stages.some((stage) => stage.event_type === "legal_acknowledged") || !stages.some((stage) => stage.event_type === "identity_declared")) return json({ error: "Legal acknowledgement and identity declaration must be completed first" }, { status: 400 });
    const approvedAt = new Date().toISOString(); const signatureName = String(body.signatureName).trim(); const approvalHash = hash([found[0].id,found[0].content_hash,actor.sub,signatureName,approvedAt].join("|")); const rows = await db`UPDATE digital_approvals SET status='approved',approved_at=${approvedAt},approved_by=${found[0].user_id},approved_by_name=${found[0].name},approved_by_email=${found[0].email},ip_address=${meta.ip},user_agent=${meta.userAgent},approval_hash=${approvalHash} WHERE id=${found[0].id} AND status='pending' AND read_confirmed_at IS NOT NULL RETURNING id,status,approved_at,approved_by_name,approved_by_email,approval_hash`; if (!rows.length) return json({ error: "Approval was already completed" }, { status: 409 }); await db`INSERT INTO approval_events (approval_id,actor_id,event_type,ip_address,user_agent,metadata) VALUES (${found[0].id},${found[0].user_id},'approved',${meta.ip},${meta.userAgent},${JSON.stringify({ approvalHash, contentHash: found[0].content_hash, termsVersion: found[0].terms_version, legalAccepted: true, typedName: signatureName })}::jsonb)`; await sendPushToAdmins({ title: "Document approved", body: `${found[0].title} was approved by the client.`, url: "/" }).catch((error) => console.error("push approval admin notification failed", error)); return json({ approval: rows[0] });
  } catch (error) { if (error instanceof Response) return error; console.error(error); return json({ error: "Approval could not be completed" }, { status: 500 }); }
};
